# stierium ONLY SUPPORTS x86_64 for now!
ARCH        := x86_64
BOOTLDR     := limine
PROTOCOL    := limine
CC          := $(HOME)/opt/cross/bin/x86_64-elf-gcc
NASM        := nasm
QEMU        := qemu-system-x86_64 

ROOT_DIR        := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
BUILD_DIR	    := $(ROOT_DIR)/.build
OBJS_DIR		:= $(BUILD_DIR)/objs
ISO_ROOT_DIR    := $(BUILD_DIR)/iso_root
BOOT_DIR        := $(ISO_ROOT_DIR)/boot
BUILD_MK        := $(ROOT_DIR)/build.mk

