ARCH        := x86_64
BOOTLDR     := limine
PROTOCOL    := limine
CC          := clang --target=aarch64-elf
NASM        := nasm
BUILD       := debug

DEBUG_CFLAGS := -g -O0
DEBUG_CPPFLAGS := -DDEBUG

RELEASE_CFLAGS := -O2



ROOT_DIR        := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
BUILD_DIR	    := $(ROOT_DIR)/.build
OBJS_DIR		:= $(BUILD_DIR)/objs
ISO_ROOT_DIR    := $(BUILD_DIR)/iso_root
BOOT_DIR        := $(ISO_ROOT_DIR)/boot

BUILD_MK        := $(ROOT_DIR)/build.mk
ARCH_MK         := $(ROOT_DIR)/arch/$(ARCH)/arch.mk

